import { NextResponse } from 'next/server';

export async function POST(req) {
  try {
    const { pages, projectName, vercelToken } = await req.json();

    if (!vercelToken) {
      return NextResponse.json({ error: 'Vercel token required', needsAuth: true }, { status: 401 });
    }

    if (!pages || pages.length === 0) {
      return NextResponse.json({ error: 'No pages provided' }, { status: 400 });
    }

    const projectSlug = (projectName || 'grogoliath-site')
      .toLowerCase()
      .replace(/[^a-z0-9-]/g, '-')
      .replace(/-+/g, '-')
      .substring(0, 50);

    const files = [];

    let indexHtml = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${projectName || 'Home'}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
      line-height: 1.6;
      color: #333;
      background: #f8f9fa;
    }
    .header {
      background: linear-gradient(135deg, #5b4cdb 0%, #4a3dc4 100%);
      color: white;
      padding: 60px 20px;
      text-align: center;
    }
    .header h1 { font-size: 3em; margin-bottom: 0.5em; }
    .header p { font-size: 1.2em; opacity: 0.9; }
    .container { max-width: 1200px; margin: 0 auto; padding: 60px 20px; }
    .grid {
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
      gap: 24px;
      margin-top: 40px;
    }
    .card {
      background: white;
      padding: 32px;
      border-radius: 16px;
      border: 2px solid #e9ecef;
      transition: all 0.3s;
      text-decoration: none;
      color: inherit;
      display: block;
    }
    .card:hover {
      border-color: #5b4cdb;
      transform: translateY(-4px);
      box-shadow: 0 12px 24px rgba(91, 76, 219, 0.15);
    }
    .card h2 { color: #5b4cdb; font-size: 1.5em; margin-bottom: 0.5em; }
    .card p { color: #666; font-size: 0.95em; }
    .footer {
      text-align: center;
      padding: 40px 20px;
      color: #666;
      border-top: 1px solid #e9ecef;
      margin-top: 60px;
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>🚀 ${projectName || 'My SEO Pages'}</h1>
    <p>${pages.length} optimized landing pages</p>
  </div>
  <div class="container">
    <h2 style="font-size: 2em; margin-bottom: 8px;">All Pages</h2>
    <p style="color: #666; margin-bottom: 20px;">Click any page to view</p>
    <div class="grid">
`;

    pages.forEach((page, index) => {
      const filename = page.slug || `page-${index + 1}`;
      const htmlPath = `${filename}.html`;

      indexHtml += `      <a href="${htmlPath}" class="card">
        <h2>${page.keyword || page.title || `Page ${index + 1}`}</h2>
        <p>${page.location || 'Location-based page'}</p>
      </a>
`;

      const pageHtml = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${page.title || page.keyword || 'Page'}</title>
  <meta name="description" content="${page.keyword || ''} - ${page.location || ''}">
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
      line-height: 1.7;
      color: #333;
      background: white;
    }
    .container { max-width: 900px; margin: 0 auto; padding: 60px 20px; }
    h1 { color: #5b4cdb; font-size: 2.5em; margin-bottom: 0.5em; line-height: 1.2; }
    h2 { color: #5b4cdb; font-size: 2em; margin-top: 1.5em; margin-bottom: 0.5em; }
    h3 { color: #4a3dc4; font-size: 1.5em; margin-top: 1.2em; margin-bottom: 0.5em; }
    p { margin: 1em 0; font-size: 1.05em; }
    .cta {
      background: linear-gradient(135deg, #5b4cdb 0%, #4a3dc4 100%);
      color: white;
      padding: 18px 36px;
      border-radius: 12px;
      display: inline-block;
      margin: 32px 0;
      text-decoration: none;
      font-weight: 600;
      font-size: 1.1em;
      transition: transform 0.2s;
    }
    .cta:hover { transform: translateY(-2px); box-shadow: 0 8px 16px rgba(91, 76, 219, 0.3); }
    .back-link {
      display: inline-block;
      margin-top: 40px;
      padding-top: 40px;
      border-top: 1px solid #e9ecef;
      color: #666;
      text-decoration: none;
    }
    .back-link:hover { color: #5b4cdb; }
  </style>
</head>
<body>
  <div class="container">
    ${page.content}
    <a href="index.html" class="back-link">← Back to all pages</a>
  </div>
</body>
</html>`;

      files.push({ file: htmlPath, data: pageHtml });
    });

    indexHtml += `    </div>
  </div>
  <div class="footer">
    <p>Generated by GroGoliath | ${pages.length} pages</p>
  </div>
</body>
</html>`;

    files.push({ file: 'index.html', data: indexHtml });

    const deployResponse = await fetch('https://api.vercel.com/v13/deployments', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${vercelToken}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        name: projectSlug,
        files,
        projectSettings: { framework: null },
        target: 'production',
      }),
    });

    if (!deployResponse.ok) {
      const errorData = await deployResponse.json();
      throw new Error(errorData.error?.message || 'Vercel deployment failed');
    }

    const deployment = await deployResponse.json();

    return NextResponse.json({
      success: true,
      url: `https://${deployment.url}`,
      deploymentId: deployment.id,
      projectName: projectSlug,
    });

  } catch (error) {
    console.error('Vercel deployment error:', error);
    return NextResponse.json({ error: error.message || 'Deployment failed', details: error.toString() }, { status: 500 });
  }
}
