import { NextResponse } from 'next/server';

function escapeXml(unsafe) {
  if (!unsafe) return '';
  return unsafe
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

export async function POST(req) {
  try {
    const { pages, projectName } = await req.json();

    if (!pages || pages.length === 0) {
      return NextResponse.json({ error: 'No pages provided' }, { status: 400 });
    }

    const siteName = projectName || 'My Site';
    const siteUrl = 'https://example.com';
    const now = new Date().toISOString();

    let wxr = `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0"
  xmlns:excerpt="http://wordpress.org/export/1.2/excerpt/"
  xmlns:content="http://purl.org/rss/1.0/modules/content/"
  xmlns:wfw="http://wellformedweb.org/CommentAPI/"
  xmlns:dc="http://purl.org/dc/elements/1.1/"
  xmlns:wp="http://wordpress.org/export/1.2/">
<channel>
  <title>${escapeXml(siteName)}</title>
  <link>${siteUrl}</link>
  <description>Generated by GroGoliath</description>
  <pubDate>${now}</pubDate>
  <language>en</language>
  <wp:wxr_version>1.2</wp:wxr_version>
  <wp:base_site_url>${siteUrl}</wp:base_site_url>
  <wp:base_blog_url>${siteUrl}</wp:base_blog_url>
  <generator>GroGoliath</generator>
`;

    pages.forEach((page, index) => {
      const postId = 1000 + index;
      const slug = page.slug || `page-${index + 1}`;
      const title = page.keyword || page.title || `Page ${index + 1}`;
      const content = page.content || '';

      wxr += `
  <item>
    <title>${escapeXml(title)}</title>
    <link>${siteUrl}/${slug}/</link>
    <pubDate>${now}</pubDate>
    <dc:creator><![CDATA[admin]]></dc:creator>
    <guid isPermaLink="false">${siteUrl}/?p=${postId}</guid>
    <description></description>
    <content:encoded><![CDATA[${content}]]></content:encoded>
    <excerpt:encoded><![CDATA[]]></excerpt:encoded>
    <wp:post_id>${postId}</wp:post_id>
    <wp:post_date>${now}</wp:post_date>
    <wp:post_date_gmt>${now}</wp:post_date_gmt>
    <wp:post_modified>${now}</wp:post_modified>
    <wp:post_modified_gmt>${now}</wp:post_modified_gmt>
    <wp:comment_status>open</wp:comment_status>
    <wp:ping_status>open</wp:ping_status>
    <wp:post_name>${slug}</wp:post_name>
    <wp:status>publish</wp:status>
    <wp:post_parent>0</wp:post_parent>
    <wp:menu_order>0</wp:menu_order>
    <wp:post_type>page</wp:post_type>
    <wp:post_password></wp:post_password>
    <wp:is_sticky>0</wp:is_sticky>
    ${page.location ? `<category domain="category" nicename="${escapeXml(page.location.toLowerCase().replace(/\s+/g, '-'))}"><![CDATA[${escapeXml(page.location)}]]></category>` : ''}
  </item>`;
    });

    wxr += `
</channel>
</rss>`;

    return NextResponse.json({
      success: true,
      xml: wxr,
      filename: `${(projectName || 'pages').replace(/[^a-z0-9]/gi, '-').toLowerCase()}.xml`,
    });

  } catch (error) {
    console.error('WordPress export error:', error);
    return NextResponse.json({ error: error.message || 'Export failed' }, { status: 500 });
  }
}
