import JSZip from 'jszip';
import { NextResponse } from 'next/server';
import { requireUser, safeError } from '../../../lib/apiAuth';

export async function POST(req) {
  const auth = await requireUser(req);
  if (auth.error) return auth.error;
  try {
    const { pages, projectName } = await req.json();

    if (!pages || pages.length === 0) {
      return NextResponse.json({ error: 'No pages provided' }, { status: 400 });
    }

    const zip = new JSZip();

    // Create index.html with links to all pages
    let indexContent = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${projectName || 'Generated Pages'}</title>
  <style>
    body {
      font-family: system-ui, -apple-system, sans-serif;
      max-width: 800px;
      margin: 40px auto;
      padding: 20px;
      line-height: 1.6;
    }
    h1 { color: #5b4cdb; }
    ul { list-style: none; padding: 0; }
    li {
      margin: 12px 0;
      padding: 16px;
      background: #f8f9fa;
      border-radius: 8px;
      border-left: 4px solid #5b4cdb;
    }
    a {
      color: #5b4cdb;
      text-decoration: none;
      font-weight: 600;
      font-size: 18px;
    }
    a:hover { text-decoration: underline; }
    .meta {
      color: #666;
      font-size: 14px;
      margin-top: 4px;
    }
  </style>
</head>
<body>
  <h1>📄 ${projectName || 'Generated Pages'}</h1>
  <p>Total pages: ${pages.length}</p>
  <ul>
`;

    // Add each page to ZIP
    pages.forEach((page, index) => {
      const filename = page.slug || `page-${index + 1}`;
      const htmlFilename = `${filename}.html`;
      const rawHtml = page.content || page.html_content || page.html || '';

      // If Claude returned a full HTML document, use it directly to avoid double-wrapping
      const isFullDoc = /^\s*<!DOCTYPE\s+html/i.test(rawHtml) || /^\s*<html/i.test(rawHtml);

      const fullHtml = isFullDoc ? rawHtml : `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${page.title || page.keyword || 'Page'}</title>
  <meta name="description" content="${page.keyword || ''} - ${page.location || ''}">
  <style>
    body { font-family: system-ui, sans-serif; line-height: 1.6; color: #333; max-width: 900px; margin: 0 auto; padding: 40px 20px; }
    h1, h2, h3 { color: #5b4cdb; margin-top: 1.5em; }
    p { margin: 1em 0; }
    .cta { background: #5b4cdb; color: white; padding: 16px 32px; border-radius: 8px; display: inline-block; margin: 20px 0; text-decoration: none; font-weight: bold; }
  </style>
</head>
<body>
  ${rawHtml}
  <hr style="margin: 40px 0; border: none; border-top: 1px solid #ddd;">
  <p style="text-align: center; color: #666; font-size: 14px;">Generated by GroGoliath | <a href="index.html">← Back to all pages</a></p>
</body>
</html>`;

      zip.file(htmlFilename, fullHtml);

      indexContent += `    <li>
      <a href="${htmlFilename}">${page.keyword || page.title || `Page ${index + 1}`}</a>
      <div class="meta">${page.location || ''}</div>
    </li>
`;
    });

    indexContent += `  </ul>
  <hr style="margin: 40px 0; border: none; border-top: 1px solid #ddd;">
  <p style="color: #666; font-size: 14px;">Generated by GroGoliath</p>
</body>
</html>`;

    zip.file('index.html', indexContent);

    zip.file('README.md', `# ${projectName || 'Generated Pages'}

## 📁 Contents

This ZIP contains ${pages.length} HTML pages generated by GroGoliath.

## 🚀 How to Use

1. Extract this ZIP file
2. Open index.html in your browser to see all pages
3. Upload to any web host (Netlify, Vercel, GitHub Pages, etc.)

## 📄 Files

- index.html - Main page with links to all generated pages
${pages.map((page, i) => `- ${page.slug || `page-${i + 1}`}.html - ${page.keyword || page.title || `Page ${i + 1}`}`).join('\n')}

## 🌐 Deployment

### Netlify (Drag & Drop)
1. Go to https://app.netlify.com/drop
2. Drag this entire folder
3. Done! Your site is live

### Vercel
1. Install Vercel CLI: npm i -g vercel
2. Run: vercel
3. Follow prompts

Generated by GroGoliath
`);

    const zipBase64 = await zip.generateAsync({ type: 'base64' });

    return NextResponse.json({
      success: true,
      data: zipBase64,
      filename: `${(projectName || 'pages').replace(/[^a-z0-9]/gi, '-').toLowerCase()}.zip`,
    });

  } catch (error) {
    return safeError('download-zip', error);
  }
}
